### ISSUE TITLE
Update Phoneinfoga

### ISSUE THREAD

**Issue by suhan-paradkar** [Yisus7u7/SysO-Termux#1]
Phoneinfoga package provided here is outdated.... better update it...

**Comment by Yisus7u7** [comment]
Packaging that version in a deb would be somewhat complicated.

**Comment by Yisus7u7** [comment]
Phoneinfoga dependencies take a long time to compile and some fail to do so, because they are thrown into golang, this is a problem, and I do not see if using the termux constructor works, apart from the project was moved to this repository:

https://pkgs-termux.github.io/pkgs.org/
